language: ruby
dist: trusty
os:
  - linux
#  - osx

rvm:
  - 2.3.3
  - 2.4.2
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

services:
  - mysql

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql.server start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql -u root -e "CREATE USER 'travis'@'127.0.0.1' IDENTIFIED BY '';"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql -u root -e "FLUSH PRIVILEGES;"; fi
  - mysql -u root -e 'CREATE DATABASE ruby_type_contracts;'
  - mysql -u root -e 'GRANT ALL ON ruby_type_contracts.* TO 'travis'@'127.0.0.1';'
  - cd arg_scanner

script:
  - gem install rake
  - rake test
  - rake install
  - cd ..
  - travis_wait 40 ./gradlew tasks
  - ./gradlew -Dmysql.user.name=travis -Dmysql.user.password=""  test